server:
  port: 8080
  tomcat:
    max-http-form-post-size: 100MB
spring:
  application:
    name: ai_challenge_week4_demo_application
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_week4_s1
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.yaml
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-v4-flash
          thinking:
            type: disabled
    mcp:
      client:
        enabled: true
        name: ai-challenge-week4-s1
        request-timeout: 30s
        initialized: false
        streamable-http:
          connections:
            deepwiki:
              url: https://mcp.deepwiki.com/mcp
