server:
  port: 8081
  tomcat:
    max-http-form-post-size: 100MB
spring:
  application:
    name: ai_challenge_week4_service2
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_week4_s2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.yaml
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-v4-flash
          thinking:
            type: disabled
    mcp:
      server:
        protocol: streamable
        name: mock-api
        version: 1.0.0
        instructions: "Mock API: случайные getColor (Синий/Зелёный/Красный) и getNumber (0–9)"

