server:
  tomcat:
    max-http-form-post-size: 100MB
spring:
  application:
    name: ai_challenge_week6
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_week6
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.yaml
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:3b
